# Generated by Django 5.2.9 on 2025-12-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.district')),
            ],
        ),
    ]
