# Generated by Django 5.2.9 on 2026-01-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('availability', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Smoothie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('Ingredients', models.CharField()),
                ('availability', models.CharField()),
            ],
        ),
    ]
