# Generated by Django 5.2.9 on 2026-01-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_ingredients_smoothie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smoothie',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
