# Generated by Django 5.2.9 on 2026-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='simg',
            field=models.ImageField(null=True, upload_to='smoothie/'),
        ),
    ]
