# Generated by Django 5.2.9 on 2026-01-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_smoothie_simg'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='price',
            field=models.IntegerField(default='100'),
        ),
    ]
