# Generated by Django 5.2.9 on 2026-01-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_smoothie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='price',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='simg',
            field=models.ImageField(null=True, upload_to='smoothie/'),
        ),
    ]
