# Generated by Django 5.2.9 on 2026-01-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_ingredients_price_ingredients_simg'),
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField()),
                ('status', models.CharField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.booking')),
                ('smoothie', models.ManyToManyField(to='app_core.smoothie')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSmoothie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField(default='100')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.customer')),
                ('ingredients', models.ManyToManyField(to='app_core.ingredients')),
            ],
        ),
    ]
