# Generated by Django 5.2.9 on 2026-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_booking_bookingdetails_customsmoothie'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='smoothie',
            field=models.ManyToManyField(to='app_core.smoothie'),
        ),
        migrations.RemoveField(
            model_name='smoothie',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
        migrations.AddField(
            model_name='smoothie',
            name='ingredients',
            field=models.ManyToManyField(to='app_core.ingredients'),
        ),
    ]
