# Generated by Django 5.2.9 on 2026-01-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_booking_smoothie_remove_smoothie_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('processing', 'processing')], default='processing', verbose_name='Enter role'),
        ),
    ]
