# Generated by Django 5.2.9 on 2026-02-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='calorie',
            field=models.IntegerField(default='100'),
        ),
    ]
