# Generated by Django 5.2.9 on 2026-02-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0016_alter_cart_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to=settings.AUTH_USER_MODEL)),
                ('smoothie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_smoothie', to='app_core.smoothie')),
            ],
        ),
    ]
