# Generated by Django 5.2.9 on 2026-02-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0017_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='smoothie',
        ),
    ]
