# Generated by Django 5.2.9 on 2026-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0018_remove_booking_smoothie'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='smoothie',
            field=models.ManyToManyField(to='app_core.smoothie'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
