# Generated by Django 5.2.9 on 2026-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0020_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='calorie',
            field=models.IntegerField(default='150'),
        ),
    ]
