# Generated by Django 5.2.9 on 2026-02-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0021_smoothie_calorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
