# Generated by Django 5.2.9 on 2026-02-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0022_remove_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='category',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='app_core.category'),
        ),
    ]
