# Generated by Django 5.2.9 on 2026-02-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0023_smoothie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='smoothie',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='app_core.booking'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_mater', to='app_core.booking')),
            ],
        ),
    ]
