# Generated by Django 5.2.9 on 2026-02-24 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0025_custombooking_custompayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customingredients',
            name='customMaster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_master', to='app_core.booking'),
        ),
    ]
