# Generated by Django 5.2.9 on 2026-02-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0026_customingredients_custommaster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customMaster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cp_master', to='app_core.custombooking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='customingredients',
            name='customMaster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_master', to='app_core.custombooking'),
        ),
        migrations.DeleteModel(
            name='CustomPayment',
        ),
    ]
