# Generated by Django 5.2.9 on 2026-02-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0027_payment_custommaster_id_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customingredients',
            old_name='Customer',
            new_name='customer',
        ),
    ]
