# Generated by Django 5.2.9 on 2026-03-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0029_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(null=True)),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='completed', verbose_name='Enter status')),
                ('customMaster_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dl_master', to='app_core.custombooking')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delv', to='app_core.delivery')),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_mater', to='app_core.booking')),
            ],
        ),
    ]
