# Generated by Django 5.2.9 on 2026-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0031_alter_deliveryupdate_master_id_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customingredients',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
