# Generated by Django 5.2.9 on 2026-03-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('location', models.CharField()),
                ('contact', models.CharField()),
                ('pincode', models.CharField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.customer')),
            ],
        ),
    ]
